In [ ]:
import numpy as np

 1. Create a 5x5 matrix with values ranging from 3 to 7

In [ ]:
a = np.zeros([5,5])

a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
A = np.arange(3,8)

A

array([3, 4, 5, 6, 7])

In [ ]:
for i in range(0,1):
    print(a+A)  

[[3. 4. 5. 6. 7.]
 [3. 4. 5. 6. 7.]
 [3. 4. 5. 6. 7.]
 [3. 4. 5. 6. 7.]
 [3. 4. 5. 6. 7.]]


2. Create and array with shape of 4x4 and turn it into two arrays along the second axis

In [ ]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
Z = np.hsplit(A,2)

In [ ]:
Z

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]